name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable
      with:
        targets: wasm32-unknown-unknown

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    - name: Wait for deployment to propagate
      run: sleep 10

    - name: Run E2E tests against production
      env:
        CF_ACCOUNT_SUBDOMAIN: imjasonh.workers.dev
      run: |
        PROD_URL="https://work-rs.${{ env.CF_ACCOUNT_SUBDOMAIN }}"
        echo "Running E2E tests against production: $PROD_URL"
        ./e2e-test.sh "$PROD_URL"
