name: Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Delete Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Delete Preview Worker
      uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: delete --name work-rs-preview-${{ github.event.pull_request.number }} --force
